### ISSUE TITLE
New Launch Options Dialog Unthemed

### ISSUE THREAD

**Issue by PhantomGamers** [AikoMidori/steam-library#22]
The latest Steam update has introduced a new Launch Options Dialog which is part of the library:

![image](https://user-images.githubusercontent.com/844685/216812034-6b5de262-c163-4671-836c-0c9300927ece.png)

This can be themed with the following classes:

```css
[class*="launchoptionsdialog_LaunchOptionDialog_"],[class*="launchoptionsdialog_ListItem_"],[class*="launchoptionsdialog_OptionList_"],[class*="launchoptionsdialog_ListContainer_"] {
    background: var(--librarybg) !important;
}
[class*="launchoptionsdialog_PlayButton_"], [class*="launchoptionsdialog_CancelButton_"] {
    background: var(--ButtonPlay) !important;
}
```

which results in 

![image](https://user-images.githubusercontent.com/844685/216812068-f91bd395-2731-4715-8607-d5782ee77110.png)

however I think this is still not themed optimally so I won't submit a PR with this specifically, needs someone else with a better eye and understanding of css to fix
